### ISSUE TITLE
Mersenne Twister

### ISSUE THREAD

**Issue by penzn** [ngzhian/simd-benchmarks#1]
I've tried building latest version of double precision SIMD-friendly Mersenne Twister (dSFMT 2.2.3) with 64-bit support. It worked out of the box with Emscripten, and I can see `f64x2` and `i64x2` instructions when building with `unimplemented-simd128`.

Project page:

http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/SFMT/index.html

My repository (same code as 2.2.3):

https://github.com/penzn/dSFMT-wasm

The flags to build are:

```
$ make CC=emcc OPTI="-O3 -munimplemented-simd128"
```

Also see penzn/dSFMT-wasm#1

**Comment by ngzhian** [comment]
I tried compiling to native to see how much speedup can be seen:

$ ./test-std-M19937 -s && echo && ./test-sse2-M19937 -s
consumed time for generating 100000000 randoms.
ST BLOCK [0, 1) AVE: 142ms.
ST BLOCK (0, 1] AVE: 139ms.
ST BLOCK (0, 1) AVE: 154ms.
ST BLOCK [1, 2) AVE: 120ms.
ST SEQ [0, 1) 1 AVE: 209ms.
ST SEQ [0, 1) 2 AVE: 254ms.
total = 500014655.815776
ST SEQ (0, 1] 1 AVE: 210ms.
ST SEQ (0, 1] 2 AVE: 253ms.
total = 500035344.184224
ST SEQ (0, 1) 1 AVE: 218ms.
ST SEQ (0, 1) 2 AVE: 283ms.
total = 500014655.815776
ST SEQ [1, 2) 1 AVE: 208ms.
ST SEQ [1, 2) 2 AVE: 251ms.
total = 1500064655.815183

consumed time for generating 100000000 randoms.
ST BLOCK [0, 1) AVE: 119ms.
ST BLOCK (0, 1] AVE: 115ms.
ST BLOCK (0, 1) AVE: 111ms.
ST BLOCK [1, 2) AVE:  60ms.
ST SEQ [0, 1) 1 AVE: 149ms.
ST SEQ [0, 1) 2 AVE: 189ms.
total = 500014655.815776
ST SEQ (0, 1] 1 AVE: 150ms.
ST SEQ (0, 1] 2 AVE: 190ms.
total = 500035344.184224
ST SEQ (0, 1) 1 AVE: 153ms.
ST SEQ (0, 1) 2 AVE: 222ms.
total = 500014655.815776
ST SEQ [1, 2) 1 AVE: 149ms.
ST SEQ [1, 2) 2 AVE: 190ms.
total = 1500064655.815183

I don't see the 2x speedup mentioned on the homepage, but there is definitely speedup.

I then built them with emcc:
emcc -O3 -DDSFMT_MEXP=19937 -o scalar.js dSFMT.c test.c -s SIMD=1
emcc -O3 -DDSFMT_MEXP=19937 -o simd.js dSFMT.c test.c -s SIMD=1 -munimplemented-simd128

And running them:

$ dd8r scalar.js -- -s
consumed time for generating 100000000 randoms.
ST BLOCK [0, 1) AVE: 203ms.
ST BLOCK (0, 1] AVE: 199ms.
ST BLOCK (0, 1) AVE: 209ms.
ST BLOCK [1, 2) AVE: 173ms.
ST SEQ [0, 1) 1 AVE: 451ms.
ST SEQ [0, 1) 2 AVE: 360ms.
total = 500014655.815776
ST SEQ (0, 1] 1 AVE: 452ms.
ST SEQ (0, 1] 2 AVE: 361ms.
total = 500035344.184224
ST SEQ (0, 1) 1 AVE: 422ms.
ST SEQ (0, 1) 2 AVE: 357ms.
total = 500014655.815776
ST SEQ [1, 2) 1 AVE: 445ms.
ST SEQ [1, 2) 2 AVE: 348ms.
total = 1500064655.815183

$ dd8r simd.js -- -s
consumed time for generating 100000000 randoms.
ST BLOCK [0, 1) AVE: 196ms.
ST BLOCK (0, 1] AVE: 191ms.
ST BLOCK (0, 1) AVE: 206ms.
ST BLOCK [1, 2) AVE: 173ms.
ST SEQ [0, 1) 1 AVE: 446ms.
ST SEQ [0, 1) 2 AVE: 352ms.
total = 500014655.815776
ST SEQ (0, 1] 1 AVE: 445ms.
ST SEQ (0, 1] 2 AVE: 360ms.
total = 500035344.184224
ST SEQ (0, 1) 1 AVE: 420ms.
ST SEQ (0, 1) 2 AVE: 353ms.
total = 500014655.815776
ST SEQ [1, 2) 1 AVE: 445ms.
ST SEQ [1, 2) 2 AVE: 347ms.
total = 1500064655.815183

And it's less clear if there is any speedup. I will look more.

Thanks for sharing this!

**Comment by ngzhian** [comment]
I'm trying to port dSFMT.c to use wasm_simd128.h intrinsics, but it's missing 32x4 shuffles, and thus falling back to v8x16 shuffle which i think is causing slowdown. I'll see what I can do there.

**Comment by ngzhian** [comment]
Ah figured out I was doing something wrong, my shuffle immediates were wrong, and so i didnt end up in an optimized (pshufd) path.
It looks better now:
$ dd8r simd.js -- -s
consumed time for generating 100000000 randoms.
ST BLOCK [0, 1) AVE: 132ms.
ST BLOCK (0, 1] AVE: 122ms.
ST BLOCK (0, 1) AVE: 122ms.
ST BLOCK [1, 2) AVE: 119ms.
ST SEQ [0, 1) 1 AVE: 401ms.
ST SEQ [0, 1) 2 AVE: 302ms.
total = 500014655.815776
ST SEQ (0, 1] 1 AVE: 402ms.
ST SEQ (0, 1] 2 AVE: 312ms.
total = 500035344.184224
ST SEQ (0, 1) 1 AVE: 377ms.
ST SEQ (0, 1) 2 AVE: 317ms.
total = 500014655.815776
ST SEQ [1, 2) 1 AVE: 400ms.
ST SEQ [1, 2) 2 AVE: 302ms.
total = 1500064655.815183

I will put up a small PR for you to take a look at the changes

**Comment by penzn** [comment]
Thank you for the PR, it looks good. Looks like some decent speedup. I am sure the algorithm is not perfectly parallelizeable, that is a good result in my opinion.

**Comment by ngzhian** [comment]
Added instructions and pointers to https://github.com/penzn/dSFMT-wasm to README, closing this out. Thanks!
